version: '3'

services:
  api:
    container_name: stock-manager-api
    working_dir: /app/backend
    build: ./backend
    command: npm run watch
    ports:
      - "3124:3000"
    volumes:
      - ./backend:/app/backend
  frontend:
    container_name: stock-manager-frontend
    working_dir: /app/frontend
    build: ./frontend
    command: npm run serve
    ports:
      - "4444:8080"
    volumes:
      - ./frontend:/app/frontend
